COPY INTO SAAS_ANALYTICS.BRONZE.SOCIAL_MEDIA_USERS_RAW
FROM (
    SELECT
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14,
        METADATA$FILENAME,
        CURRENT_TIMESTAMP()
    FROM @SAAS_ANALYTICS.BRONZE.RAW_STAGE
)
FILE_FORMAT = SAAS_ANALYTICS.COMMON.CSV_FORMAT;