USE ROLE SYSADMIN;

-- ====================================================================================
-- DYNAMIC DATA MASKING POLICIES
-- ====================================================================================
-- This file creates and applies masking policies to sensitive columns
--
-- Data Visibility:
--   - SYSADMIN: Full unmasked access
--   - ANALYST_ROLE: Full unmasked access
--   - QA_ROLE: Masked view of sensitive data
--   - Others: NULL (no access)
--
-- Roles: SYSADMIN (built-in), ANALYST_ROLE, QA_ROLE (see 00_database_setup/03_create_roles.sql)
-- ====================================================================================

-- Masking policy for STRING columns
CREATE MASKING POLICY IF NOT EXISTS SAAS_ANALYTICS.GOVERNANCE.SOCIAL_MEDIA_USERS_STRING_MASKING_POLICY
AS (VAL STRING)
RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN ('ANALYST_ROLE') THEN VAL
    ELSE '***MASKED***'
END;

-- Masking policy for NUMBER columns
CREATE MASKING POLICY IF NOT EXISTS SAAS_ANALYTICS.GOVERNANCE.SOCIAL_MEDIA_USERS_NUMBER_MASKING_POLICY
AS (VAL NUMBER)
RETURNS NUMBER ->
CASE
    WHEN CURRENT_ROLE() IN ('ANALYST_ROLE') THEN VAL
    ELSE -999  -- can't return a string like '***MASKED***' for a NUMBER, so NULL is the convention
END;

-- Apply STRING masking policy to numeric health columns
ALTER TABLE SAAS_ANALYTICS.SILVER.SOCIAL_MEDIA_USERS_CLEAN
MODIFY COLUMN gender SET MASKING POLICY SAAS_ANALYTICS.GOVERNANCE.SOCIAL_MEDIA_USERS_STRING_MASKING_POLICY;

-- Apply NUMBER masking policy to numeric health columns
ALTER TABLE SAAS_ANALYTICS.SILVER.SOCIAL_MEDIA_USERS_CLEAN
MODIFY COLUMN age SET MASKING POLICY SAAS_ANALYTICS.GOVERNANCE.SOCIAL_MEDIA_USERS_NUMBER_MASKING_POLICY;

ALTER TABLE SAAS_ANALYTICS.SILVER.SOCIAL_MEDIA_USERS_CLEAN
MODIFY COLUMN body_mass_index SET MASKING POLICY SAAS_ANALYTICS.GOVERNANCE.SOCIAL_MEDIA_USERS_NUMBER_MASKING_POLICY;

ALTER TABLE SAAS_ANALYTICS.SILVER.SOCIAL_MEDIA_USERS_CLEAN
MODIFY COLUMN blood_pressure_systolic SET MASKING POLICY SAAS_ANALYTICS.GOVERNANCE.SOCIAL_MEDIA_USERS_NUMBER_MASKING_POLICY;

ALTER TABLE SAAS_ANALYTICS.SILVER.SOCIAL_MEDIA_USERS_CLEAN
MODIFY COLUMN blood_pressure_diastolic SET MASKING POLICY SAAS_ANALYTICS.GOVERNANCE.SOCIAL_MEDIA_USERS_NUMBER_MASKING_POLICY;