CREATE OR REPLACE MASKING POLICY SAAS_ANALYTICS.GOVERNANCE.AGE_MASKING_POLICY
AS (VAL STRING) 
RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN ('ANALYST_ROLE') THEN '****'
    ELSE VAL
END;

-- Apply to Silver table
ALTER TABLE SAAS_ANALYTICS.SILVER.SOCIAL_MEDIA_USERS_CLEAN
MODIFY COLUMN age
SET MASKING POLICY SAAS_ANALYTICS.GOVERNANCE.AGE_MASKING_POLICY;