-- ====================================================================================
-- DYNAMIC DATA MASKING POLICIES
-- ====================================================================================
-- This file creates and applies masking policies to sensitive columns
-- Roles: SYSADMIN (built-in), ANALYST_ROLE (see 00_database_setup/03_create_roles.sql)
-- ====================================================================================

-- Create masking policy for sensitive health data
CREATE OR REPLACE MASKING POLICY SAAS_ANALYTICS.GOVERNANCE.SENSITIVE_DATA_MASKING_POLICY
AS (VAL STRING) 
RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN ('SYSADMIN') THEN VAL
    WHEN CURRENT_ROLE() IN ('ANALYST_ROLE') THEN '***MASKED***'
    ELSE NULL
END;

-- Apply masking to sensitive columns
ALTER TABLE SAAS_ANALYTICS.SILVER.SOCIAL_MEDIA_USERS_CLEAN
MODIFY COLUMN age SET MASKING POLICY SAAS_ANALYTICS.GOVERNANCE.SENSITIVE_DATA_MASKING_POLICY;

ALTER TABLE SAAS_ANALYTICS.SILVER.SOCIAL_MEDIA_USERS_CLEAN
MODIFY COLUMN body_mass_index SET MASKING POLICY SAAS_ANALYTICS.GOVERNANCE.SENSITIVE_DATA_MASKING_POLICY;

ALTER TABLE SAAS_ANALYTICS.SILVER.SOCIAL_MEDIA_USERS_CLEAN
MODIFY COLUMN blood_pressure_systolic SET MASKING POLICY SAAS_ANALYTICS.GOVERNANCE.SENSITIVE_DATA_MASKING_POLICY;

ALTER TABLE SAAS_ANALYTICS.SILVER.SOCIAL_MEDIA_USERS_CLEAN
MODIFY COLUMN blood_pressure_diastolic SET MASKING POLICY SAAS_ANALYTICS.GOVERNANCE.SENSITIVE_DATA_MASKING_POLICY;