CREATE OR REPLACE ROW ACCESS POLICY SAAS_ANALYTICS.GOVERNANCE.TENANT_RLS
AS (TENANT_ID STRING) RETURNS BOOLEAN ->
CURRENT_ROLE() IN ('ADMIN_ROLE') OR CURRENT_ROLE() = TENANT_ID;

-- Apply to Silver table
ALTER TABLE SAAS_ANALYTICS.SILVER.SOCIAL_MEDIA_USERS_CLEAN
ADD ROW ACCESS POLICY SAAS_ANALYTICS.GOVERNANCE.TENANT_RLS ON (TENANT_ID);