USE ROLE SYSADMIN;

-- ====================================================================================
-- ORCHESTRATION TASKS FOR GOLD LAYER
-- ====================================================================================
-- These tasks schedule the gold layer procedures to run on a regular basis
-- Runs after silver layer transformations to ensure dependent data is ready
-- ====================================================================================


CREATE OR REPLACE TASK SAAS_ANALYTICS.ORCHESTRATION.TASK_LOAD_TENANT_ENGAGEMENT_METRICS
WAREHOUSE = SAAS_WH
AFTER TASK_TRANSFORM_BRONZE_TO_SILVER
AS
CALL SAAS_ANALYTICS.GOLD.LOAD_TENANT_ENGAGEMENT_METRICS();

-- Resume the task (tasks are created in suspended state by default)
ALTER TASK SAAS_ANALYTICS.ORCHESTRATION.TASK_LOAD_TENANT_ENGAGEMENT_METRICS RESUME;

-- Display task details
DESCRIBE TASK SAAS_ANALYTICS.ORCHESTRATION.TASK_LOAD_TENANT_ENGAGEMENT_METRICS;



CREATE OR REPLACE TASK SAAS_ANALYTICS.ORCHESTRATION.TASK_LOAD_USER_ENGAGEMENT_SNAPSHOT
WAREHOUSE = SAAS_WH
AFTER TASK_TRANSFORM_BRONZE_TO_SILVER
AS
CALL SAAS_ANALYTICS.GOLD.LOAD_USER_ENGAGEMENT_SNAPSHOT();

-- Resume the task (tasks are created in suspended state by default)
ALTER TASK SAAS_ANALYTICS.ORCHESTRATION.TASK_LOAD_USER_ENGAGEMENT_SNAPSHOT RESUME;

-- Display task details
DESCRIBE TASK SAAS_ANALYTICS.ORCHESTRATION.TASK_LOAD_USER_ENGAGEMENT_SNAPSHOT;



CREATE OR REPLACE TASK SAAS_ANALYTICS.ORCHESTRATION.TASK_LOAD_CONTENT_PERFORMANCE_METRICS
WAREHOUSE = SAAS_WH
AFTER TASK_TRANSFORM_BRONZE_TO_SILVER
AS
CALL SAAS_ANALYTICS.GOLD.LOAD_CONTENT_PERFORMANCE_METRICS();

-- Resume the task (tasks are created in suspended state by default)
ALTER TASK SAAS_ANALYTICS.ORCHESTRATION.TASK_LOAD_CONTENT_PERFORMANCE_METRICS RESUME;

-- Display task details
DESCRIBE TASK SAAS_ANALYTICS.ORCHESTRATION.TASK_LOAD_CONTENT_PERFORMANCE_METRICS;