USE ROLE SYSADMIN;


ALTER TASK SAAS_ANALYTICS.ORCHESTRATION.TASK_LOAD_TENANT_ENGAGEMENT_METRICS RESUME;
ALTER TASK SAAS_ANALYTICS.ORCHESTRATION.TASK_LOAD_USER_ENGAGEMENT_SNAPSHOT RESUME;
ALTER TASK SAAS_ANALYTICS.ORCHESTRATION.TASK_LOAD_CONTENT_PERFORMANCE_METRICS RESUME;


ALTER TASK SAAS_ANALYTICS.ORCHESTRATION.TASK_TRANSFORM_BRONZE_TO_SILVER RESUME;


ALTER TASK SAAS_ANALYTICS.ORCHESTRATION.TASK_DAILY_LOAD_BRONZE_DATA RESUME;