USE ROLE SYSADMIN;

CREATE OR REPLACE STREAM SAAS_ANALYTICS.BRONZE.SOCIAL_MEDIA_USERS_STREAM
ON TABLE SAAS_ANALYTICS.BRONZE.SOCIAL_MEDIA_USERS_RAW
APPEND_ONLY = FALSE;  -- Tracks inserts, updates, deletes