CREATE SCHEMA IF NOT EXISTS SAAS_ANALYTICS.BRONZE;
CREATE SCHEMA IF NOT EXISTS SAAS_ANALYTICS.SILVER;
CREATE SCHEMA IF NOT EXISTS SAAS_ANALYTICS.GOLD;
CREATE SCHEMA IF NOT EXISTS SAAS_ANALYTICS.COMMON;
CREATE SCHEMA IF NOT EXISTS SAAS_ANALYTICS.ORCHESTRATION;
CREATE SCHEMA IF NOT EXISTS SAAS_ANALYTICS.GOVERNANCE;