USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS SAAS_ANALYTICS;

-- ====================================================================================
-- GRANT USAGE ON DATABASE TO FUNCTIONAL ROLES
-- ====================================================================================

GRANT USAGE ON DATABASE SAAS_ANALYTICS TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE SAAS_ANALYTICS TO ROLE QA_ROLE;
GRANT USAGE ON DATABASE SAAS_ANALYTICS TO ROLE DEVELOPER_ROLE;

-- ====================================================================================
-- DATABASE USAGE — DASHBOARD VIEWER ROLES
-- ====================================================================================

GRANT USAGE ON DATABASE SAAS_ANALYTICS TO ROLE SOCIAL_DASHBOARD_AMERICAS_VIEWER;
GRANT USAGE ON DATABASE SAAS_ANALYTICS TO ROLE SOCIAL_DASHBOARD_EUROPE_VIEWER;
GRANT USAGE ON DATABASE SAAS_ANALYTICS TO ROLE SOCIAL_DASHBOARD_ASIA_PACIFIC_VIEWER;
GRANT USAGE ON DATABASE SAAS_ANALYTICS TO ROLE SOCIAL_DASHBOARD_AUSTRALIA_VIEWER;
