USE ROLE SYSADMIN;

CREATE SCHEMA IF NOT EXISTS SAAS_ANALYTICS.BRONZE;
CREATE SCHEMA IF NOT EXISTS SAAS_ANALYTICS.SILVER;
CREATE SCHEMA IF NOT EXISTS SAAS_ANALYTICS.GOLD;
CREATE SCHEMA IF NOT EXISTS SAAS_ANALYTICS.COMMON;
CREATE SCHEMA IF NOT EXISTS SAAS_ANALYTICS.ORCHESTRATION;
CREATE SCHEMA IF NOT EXISTS SAAS_ANALYTICS.GOVERNANCE;

-- ====================================================================================
-- GRANT SCHEMA PRIVILEGES
-- ====================================================================================

-- ANALYST_ROLE - Full read access to Silver and Gold schemas (no masking applied)
GRANT USAGE ON SCHEMA SAAS_ANALYTICS.SILVER TO ROLE ANALYST_ROLE;
GRANT USAGE ON SCHEMA SAAS_ANALYTICS.GOLD TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SAAS_ANALYTICS.SILVER TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SAAS_ANALYTICS.GOLD TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SAAS_ANALYTICS.SILVER TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SAAS_ANALYTICS.GOLD TO ROLE ANALYST_ROLE;

-- QA_ROLE - Read-only access to Silver and Gold schemas (with data masking applied)
GRANT USAGE ON SCHEMA SAAS_ANALYTICS.SILVER TO ROLE QA_ROLE;
GRANT USAGE ON SCHEMA SAAS_ANALYTICS.GOLD TO ROLE QA_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SAAS_ANALYTICS.SILVER TO ROLE QA_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SAAS_ANALYTICS.GOLD TO ROLE QA_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SAAS_ANALYTICS.SILVER TO ROLE QA_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SAAS_ANALYTICS.GOLD TO ROLE QA_ROLE;

-- DEVELOPER_ROLE - Full access to Bronze, Silver, Orchestration for ETL work
GRANT ALL PRIVILEGES ON SCHEMA SAAS_ANALYTICS.BRONZE TO ROLE DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA SAAS_ANALYTICS.SILVER TO ROLE DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA SAAS_ANALYTICS.GOLD TO ROLE DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA SAAS_ANALYTICS.ORCHESTRATION TO ROLE DEVELOPER_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA SAAS_ANALYTICS.COMMON TO ROLE DEVELOPER_ROLE;